baseURL = 'https://curso-modelos-basados-en-agentes.github.io/curso_MBA/'
languageCode = 'es-MX'
title = 'Modelado basados en agentes'
defaultContentLanguage = 'es'
theme = 'hugo-book'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]

BookTheme = 'light'
BookToC = true
BookLogo = 'logo.png'
BookSection = '*'
BookRepo = 'https://github.com/Curso-Modelos-Basados-en-Agentes/curso_MBA.git'
BookCommitPath = 'commit'
BookSearch = true